version: '3'
services:

    wordpress:
        container_name: wordpress
        build:
            context: etc/wordpress
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        restart: always
        depends_on:
            - mysql
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_NAME: db_fiap
            WORDPRESS_DB_USER: admdimdim
            WORDPRESS_DB_PASSWORD: Fiap2tdst2021

    mysql:
        container_name: mysql
        build:
            context: etc/mysql
            dockerfile: Dockerfile
        ports:
            - "3307:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_fiap
            MYSQL_USER: admdimdim
            MYSQL_PASSWORD: Fiap2tdst2021

    phpmyadmin:
        container_name: phpmyadmin
        build:
            context: etc/phpmyadmin
            dockerfile: Dockerfile
        ports:
            - "8081:80"
        restart: always
        depends_on:
            - mysql
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mysql
